language: cpp

compiler:
  - gcc

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install libopenmpi-dev

script: 
  - scons program=kaffpa variant=optimized 
  - cd parallel; cd modified_kahip; scons program=library variant=optimized; cp modified_kahip/optimized/libkahip.a parallel_src/extern/kaHIP_lib/; cp modified_kahip/optimized/kaHIP_interface.h parallel_src/extern/kaHIP_lib/; cd ../parallel_src/; scons program=parhip variant=optimized_nooutput; cd ../../ 
  - scons program=node_separator variant=optimized 
  - scons program=evaluator variant=optimized 
  - scons program=kaffpaE variant=optimized 
  - scons program=graphchecker variant=optimized 
  - scons program=label_propagation variant=optimized 
  - scons program=library variant=optimized 
  - scons program=partition_to_vertex_separator variant=optimized 
